### ISSUE TITLE
issue with 0.13

### ISSUE THREAD

**Issue by rogueturnip** [dwmkerr/app-icon#115]
I've been using app-icon for a while in MS Appcenter for building.  It's running a Mac OS X (Mojave I think) with Node 10.x.  With the recent build I'm getting the following error.  If I use 0.11.0 everything works fine.

/usr/local/lib/node_modules/app-icon/bin/app-icon.js:16
const errorIfMissing = async (filePath, errorMessage) => {
                             ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by dwmkerr** [comment]
That's odd - can you share the output of the below command?

```
node -v
```

Just out of curiosity?
